### ISSUE TITLE
checkout ok,but commit error，why

### ISSUE THREAD

**Issue by be-engineer** [userid0x0/svn-docker#1]
I used docker to build a svn-docker server, and then used svnadmin to create a new warehouse. I can checkout the warehouse with the svn client, but when I add a file and submit it, it prompts:
```
$ svn ci -m "add file"
svn: E175013: Commit failed (details below):
svn: E175013: Access to '/svn/repos/!svn/me' is forbidden
```
I do not know why？

**Comment by userid0x0** [comment]
Check `Access-Paths` in svnadmin, the default is that all repositories are read-only for everyone (should be signaled by a asterisk `*` by svnadmin). Thanks for pointing that out - I can add this to the quick-start steps.

**Comment by userid0x0** [comment]
I updated the `README.md`, let me know if this helps.

**Comment by be-engineer** [comment]
yes,it worked,thanks
