### ISSUE TITLE
svn "view history" and config errors

### ISSUE THREAD

**Issue by be-engineer** [userid0x0/svn-docker#2]
I can view svn repo in browser,but when I click "view history" button, I get some error message--"The log script must be configured with a root URL", what's wrong?

![image](https://user-images.githubusercontent.com/16242748/236105688-b81e45ca-24f3-4b46-a771-fad918f0108f.png)

And another issue is in http://ip/svnadmin

![image](https://user-images.githubusercontent.com/16242748/236106398-11291ecd-459f-41c4-9c64-4a19365a9167.png)

When I click "save configuration" button,I got some error messages:
```
Error: flock(): Argument #1 ($stream) must be of type resource, bool given
#0 /opt/svnadmin/include/ifcorelib/IF_IniFile.func.php(108): flock()
#1 /opt/svnadmin/include/ifcorelib/IF_IniFile.class.php(62): if_write_ini_file()
#2 /opt/svnadmin/settings.php(130): IF_IniFile->saveToFile()
#3 {main}
```

**Comment by userid0x0** [comment]
Thanks for reporting.
# 1
The broken log view seems to be a missing configuration in the repos-style XSLT. I can later on try to fix that.
You may use `websvn` for the moment.
# 2
Well, the if.svnadmin wasn't developed for PHP8.1, looks like I missed something while porting.
Anyhow, the configuration for the container is expected to be fixed/ready. Thus there is no urgent need to use this dialog. Correct me if I am wrong.

**Comment by userid0x0** [comment]
I put a fix for the missing histrory functionality. Unfortunately the underlying script doesn't support `svnauthz`. Thus I introduced `SVN_SERVER_REPOS_STYLE_AUTH`. See also:
https://github.com/userid0x0/svn-docker/commit/82413d6564e0ac44e1190edc3c54707bf9f1b274
.

**Comment by userid0x0** [comment]
Hi,
please do another `docker pull` the `v3.17` & `latest` tags contain the fixes.
Please note the new `SVN_SERVER_REPOS_STYLE_AUTH` environment variable.
