### ISSUE TITLE
warning message when browse repository with svnadmin

### ISSUE THREAD

**Issue by chjq68** [userid0x0/svn-docker#8]
message as following in top of broser:
 (/usr/bin/svn error=svn: warning: W000013: Can't open file '/root/.subversion/servers': Permission denied
)

"/usr/bin/svn" ls --xml --non-interactive --trust-server-cert file:///data/repositories/doc/

what's the problem?
(I configured open ldap auth for svnadmin)

![image](https://github.com/user-attachments/assets/5161a62b-6b46-4a73-8161-b7ed3eaf7c0e)

**Comment by userid0x0** [comment]
Hi,
I need to apologize for the delay. I never used LDAP so far, I can try to reproduce the problem the next days.
Without LDAP I haven't seen this behavior.
Did you do any special bind-/volume-mounts?

**Comment by chjq68** [comment]
I use bindfs to mount reository fold for use of redmine, this is the file /etc/fstab:
/data/autoit/data/svn2/data/repositories /data/autoit/data/redmine511/repos-svn fuse.bindfs rw,force-user=0,force-group=0 0 0

then load for redmine in docker-compoe file:
redmine511:
 ......
- '../data/redmine511/repos-svn:/usr/src/repos-svn:ro'

  svn-server:
    image: 'userid0x0/svn-docker:v3.19'
    hostname: 'svn.co-think.com'
    restart: 'always'
    environment:
      SVN_SERVER_REPOSITORIES_URL: "/svn"
      WEBSVN_URL: "/websvn"
      WEBSVN_AUTH: "2"
      SVN_SERVER_REPOS_STYLE_AUTH: "2"

    volumes:
      - '../data/svn2/data:/data'
    ports:
      - '3690:3690'
      - '8081:80'

To make LDAP work, I pachted manually as:
https://github.com/mfreiholz/iF.SVNAdmin/pull/137
(I'm not sure wether this problem is related with LDAP).

**Comment by userid0x0** [comment]
Hi,
it took me a while to find time. Basically the Apache webserver used the Environment of the `root` user which runs the `s6` system. Thus User `apache` tried to access `$HOME/.subversion` -> `/root/.subversion/...` .
I changed a couple of more things and removed the user `apache` completely and use user `svn` instead. Actually this would open the possibility to enable ENV vars like `UID/GID` as for other images.

**Comment by userid0x0** [comment]
Hi,
there is a new tag `v3.20-lsio` which uses the `linuxserver.io` image as a basis. Thus it's now possible to set the UID/GID to be used within the container.
Feel free to provide feedback.
